name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.7.0
  data: ^0.15.1
  drift: ^2.28.1
  drift_dev: ^2.28.1
  drift_flutter: ^0.2.5
  easy_localization: ^3.0.8
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_slidable: ^4.0.1
  get_it: ^8.2.0
  go_router: ^16.2.1
  image_picker: ^1.2.0
  mockito: ^5.5.0
  mocktail: ^1.0.4
  path: ^1.9.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.39
  syncfusion_flutter_calendar: ^30.2.7
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
